[project]
name = "ceu-modern-data-platforms"
version = "1.0.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "dbt-core~=1.11.0",
    "dbt-snowflake~=1.11.0",
    "dbt-autofix",
    "sqlfluff>=4.0.0",
    "sqlfluff-templater-dbt>=4.0.0",
]
